### ISSUE TITLE
bug with stairs

### ISSUE THREAD

**Issue by Cacmonkey** [aki-art/asphalt-stairs#1]
when im playing on the steam workshop version,my dupes keep dropping the items they are carring while on the stairs,not sure if its just this or both forms of the stairs mod

**Comment by aki-art** [comment]
Hi!

This is a known issue with the original mod. 
Make sure every stair has a tile under it; either another stair, or an actual tile. If it's just hanging by itself it won't work correctly.

[Discussion of the same error on Stairs Steam page](https://steamcommunity.com/workshop/filedetails/discussion/2012810337/1743395251237809088/)
